__author__ = 'k.vasileiou'
'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''
all_fibo_nums =set()
i = 1
j = 2
sum = 0
while(i<4000000 and j< 4000000):
    all_fibo_nums.add(i)
    all_fibo_nums.add(j)
    temp = i
    i=j
    j=temp+j

for k in all_fibo_nums:
    if (k%2 ==0):
        sum += k
print(sum)